# Generated by Django 6.0.3 on 2026-03-13 16:55

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=products.models.generate_product_id, help_text='Unique product identifier', max_length=50, unique=True),
        ),
    ]
